export const Constants = {
  OPEN_MODAL_ACTION: "OPEN_MODAL_ACTION",
  CLOSE_MODAL_ACTION: "CLOSE_MODAL_ACTION",
  ADD_FORM_ITEM_ACTION: "ADD_FORM_ITEM_ACTION",
  REMOVE_FORM_ITEM_ACTION: "REMOVE_FORM_ITEM_ACTION",
  SET_FORM_ID_ACTION: "SET_FORM_ID_ACTION",
  GET_FORM_ITEMS_ACTION: "GET_FORM_ITEMS_ACTION",
  SET_FORM_TITLE_ACTIONS: "SET_FORM_TITLE_ACTIONS",
  SET_FORM_DESC_ACTIONS: "SET_FORM_DESC_ACTIONS",
};
